# Generated by Django 3.2.15 on 2022-09-19 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, verbose_name='название проекта')),
                ('link', models.URLField(verbose_name='ссылка на репозиторий')),
                ('is_active', models.BooleanField(default=True, verbose_name='проект в работе')),
                ('deadline', models.DateField(verbose_name='срок окончания проекта')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='дата начала проекта')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='участники')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ('-is_active', 'deadline'),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=128, verbose_name='задача')),
                ('description', models.CharField(max_length=340, verbose_name='содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создание')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('deadline', models.DateField(verbose_name='срок окончания проекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'задача по проекту',
                'verbose_name_plural': 'задачи по проекту',
                'ordering': ('-is_active', 'deadline'),
            },
        ),
    ]
