# Generated by Django 4.2.7 on 2023-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(blank=True, default='/home/soul/Projects/DRF/drf/project_storage/', max_length=246),
        ),
    ]
