# Generated by Django 4.2.7 on 2023-12-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_note_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='проект', to='projects.project', verbose_name='Проект'),
        ),
    ]
